export const data = [
  {
    id: 1,
    image: "./images/slider/lambo-0.png",
    title: "Lamborghini 1",
    priceOfDay: 120,
    priceOfMonth: 5000,
    gear: 6,
  },
  {
    id: 2,
    image: "./images/slider/lambo-1.png",
    title: "Lamborghini 2",
    priceOfDay: 125,
    priceOfMonth: 7400,
    gear: 6,
  },
  {
    id: 3,
    image: "./images/slider/lambo-2.png",
    title: "Lamborghini 3",
    priceOfDay: 126,
    priceOfMonth: 6870,
    gear: 6,
  },
  {
    id: 4,
    image: "./images/slider/lambo-3.png",
    title: "Lamborghini 4",
    priceOfDay: 132,
    priceOfMonth: 7800,
    gear: 6,
  },
  {
    id: 5,
    image: "./images/slider/lambo-4.png",
    title: "Lamborghini 5",
    priceOfDay: 134,
    priceOfMonth: 7777,
    gear: 6,
  },
  {
    id: 6,
    image: "./images/slider/lambo-5.png",
    title: "Lamborghini 6",
    priceOfDay: 129,
    priceOfMonth: 7129,
    gear: 6,
  },
];
