export const settings = {
  xxxl: {
    className: "center",
    centerMode: true,
    centerPadding: "40px",
    autoplay: true,
    autoplaySpeed: 4000,
    pauseOnHover: true,
    slidesToShow: 3,
    speed: 900,
    dots: true,
    rtl: true,
  },
  xxl: {
    className: "center",
    centerMode: true,
    centerPadding: "120px",
    autoplay: true,
    autoplaySpeed: 4000,
    pauseOnHover: true,
    slidesToShow: 2,
    speed: 500,
    dots: true,
    rtl: true,
  },
  xl: {
    className: "center",
    centerMode: true,
    centerPadding: "230",
    autoplay: true,
    autoplaySpeed: 4000,
    pauseOnHover: true,
    slidesToShow: 1,
    speed: 500,
    dots: true,
    rtl: true,
  },
  lg: {
    className: "center",
    centerMode: true,
    centerPadding: "180px",
    autoplay: true,
    autoplaySpeed: 4000,
    pauseOnHover: true,
    slidesToShow: 1,
    speed: 500,
    dots: true,
    rtl: true,
  },
  md: {
    className: "center",
    centerMode: true,
    centerPadding: "150px",
    autoplay: true,
    autoplaySpeed: 4000,
    pauseOnHover: true,
    slidesToShow: 1,
    speed: 500,
    dots: true,
    rtl: true,
  },
  sm: {
    className: "center",
    centerMode: true,
    centerPadding: "30",
    autoplay: true,
    autoplaySpeed: 4000,
    pauseOnHover: true,
    slidesToShow: 1,
    speed: 500,
    dots: true,
    rtl: true,
  },
};
